Update deployment paths to consolidate output directory
Changed the OutputDirectory from Deploy/OUT to Deploy and updated related paths in the build workflow. This ensures consistency in deployment directories and simplifies file handling during CI/CD processes.

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -27,7 +27,7 @@ jobs:
         uses: actions/upload-artifact@v4.4.1
         with:
           name: build-output
-          path: Deploy\OUT
+          path: Deploy
 
   release:
     needs: build
@@ -37,9 +37,9 @@ jobs:
         uses: actions/download-artifact@v4.1.8
         with:
           name: build-output
-          path: Deploy/OUT
+          path: Deploy
       - name: Check if file exists
-        run: if [ ! -f Deploy/OUT/Avalonia.CoffeeShop.exe ]; then echo "File not found!"; exit 1; fi
+        run: if [ ! -f Deploy\Avalonia.CoffeeShop.exe ]; then echo "File not found!"; exit 1; fi
       - name: Create GitHub Release
         id: create_release
         uses: actions/create-release@v1
@@ -56,6 +56,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: Deploy\OUT\Avalonia.CoffeeShop.exe
+          asset_path: Deploy\Avalonia.CoffeeShop.exe
           asset_name: Avalonia.CoffeeShop.exe
           asset_content_type: application/exe
